### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by jisuz** [Sky24n/common_utils#11]
你好，我使用了你的库里面的日志打印，出现了MissingPluginException(No implementation found for method logE on channel x_log)
请问是什么原因导致的，是我的配置不对吗？
环境：
sdk: ">=2.1.0 <3.0.0"
common_utils: ^1.1.3

具体的日志内容如下：
E/flutter (20889): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method logE on channel x_log)
E/flutter (20889): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
E/flutter (20889): <asynchronous suspension>
E/flutter (20889): #1      Log.e (package:ddw/utils/log_utils.dart:39:16)
E/flutter (20889): #2      HttpUtil._onError (package:ddw/framework/net/http_util.dart:174:9)
E/flutter (20889): #3      HttpUtil.requestNetwork.<anonymous closure> (package:ddw/framework/net/http_util.dart:120:9)
E/flutter (20889): #4      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (20889): #5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (20889): #6      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
E/flutter (20889): #7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
E/flutter (20889): #8      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
E/flutter (20889): #9      Future._completeWithValue (dart:async/future_impl.dart:522:5)
E/flutter (20889): #10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
E/flutter (20889): #11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
E/flutter (20889): #12     HttpUtil._request (package:ddw/framework/net/http_util.dart)
E/flutter (20889): <asynchronous suspension>
E/flutter (20889): #13     HttpUtil.requestNetwork (package:ddw/framework/net/http_util.dart:103:18)
E/flutter (20889): <asynchronous suspension>
E/flutter (20889): #14     _LoginPageState._login (package:ddw/pages/login/page/login_page.dart:143:29)
E/flutter (20889): <asynchronous suspension>
E/flutter (20889): #15     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:654:14)
E/flutter (20889): #16     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:729:32)
E/flutter (20889): #17     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (20889): #18     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
E/flutter (20889): #19     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:312:7)
E/flutter (20889): #20     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (20889): #21     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter (20889): #22     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (20889): #23     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (20889): #24     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (20889): #25     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (20889): #26     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (20889): #27     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (20889): #28     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (20889): #29     _invoke1 (dart:ui/hooks.dart:263:10)
E/flutter (20889): #30     _dispatchPointerDataPacket (dart:ui/hooks.dart:172:5)
E/flutter (20889):

**Comment by Sky24n** [comment]
跟库没有关系，应该是你环境的问题。你可以把util屏蔽了试试


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by jisuz** [comment]
谢谢哈，找到原因了，没有吧底层的x_log配置上去

**Comment by yyloveruancaipu** [comment]
@jisuz 你好 你说的底层的x_log配置上去，是指什么？LogUtil.init()?
