### ISSUE TITLE
請問如何格式化輸出12小時制的 AM/PM？

### ISSUE THREAD

**Issue by winsonet** [Sky24n/common_utils#12]
如題啦，謝謝！

**Comment by bigbirdhzp** [comment]
看flutter-gallery源代码

**Comment by winsonet** [comment]
請問 flutter-gallery 源碼在哪呢？

**Comment by bigbirdhzp** [comment]
> 請問 flutter-gallery 源碼在哪呢？

https://github.com/Sky24n/common_utils/issues/12#issuecomment-553247062

**Comment by bigbirdhzp** [comment]
> 請問 flutter-gallery 源碼在哪呢？

https://github.com/flutter/flutter/tree/master/examples/flutter_gallery
