### ISSUE TITLE
[text_util.dart]格式化参数存在问题

### ISSUE THREAD

**Issue by yunhe-lin** [Sky24n/common_utils#19]
/// 每隔 x位 加 pattern, 从末尾开始
  static String formatDigitPatternEnd(String text,
      {int digit = 4, String pattern = ' '}) {
    String temp = reverse(text);
    temp = formatDigitPattern(temp, digit: 3, pattern: ',');
    temp = reverse(temp);
    return temp;
  }

pattern 参数问题

**Comment by Sky24n** [comment]
已知晓，谢谢~


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
