### ISSUE TITLE
1323 这种秒数怎么转化 1:05:55 这种呢？

### ISSUE THREAD

**Issue by songguowei** [Sky24n/common_utils#20]

**Comment by Sky24n** [comment]
时间戳秒?


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by songguowei** [comment]
> 时间戳秒?
> 
> :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

不是就是int类型 转1:05:55这种格式

**Comment by Sky24n** [comment]
如果是时间戳秒：
DateUtil.formatDate(秒*1000, format: DataFormats.h_m_s)
or
DateUtil.formatDate(秒*1000, format: "HH:mm:ss")
