### ISSUE TITLE
DateUtil.getDateStrByMs在1.2版本中不存在

### ISSUE THREAD

**Issue by byteslaves** [Sky24n/common_utils#24]
我项目使用的是flustars: ^0.2.6+1，使用的是common_utils1.1.3，在新环境flutter pub get 拉取的是1.2版本，报错DateUtil.getDateStrByMs不存在。在yaml文件添加common_utils1.1.3插件依赖版本还是不行，请问要怎么处理啊

**Comment by Sky24n** [comment]
用新api替换下就行了啊！ 
DateUtil.formatDateMs()
common_utils最新1.2.1了，改了很多东西。
目前最新 flustars: ^0.3.2

**Comment by byteslaves** [comment]
> 用新api替换下就行了啊！
> DateUtil.formatDateMs()
> common_utils最新1.2.1了，改了很多东西。
> 目前最新 flustars: ^0.3.2

好，我试试，谢谢了
