### ISSUE TITLE
SpUtil 会不会使应用启动变慢

### ISSUE THREAD

**Issue by leetomlee123** [Sky24n/common_utils#28]
`  await SpUtil.getInstance();`

我是用sp保存小说章节  app使用越久 sp key越多   应用启动越慢

这是我遇到的问题 以及我的猜测

**Comment by Sky24n** [comment]
sp本来就是用来存简单数据的!


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by leetomlee123** [comment]
ojbk  得该一波了
