### ISSUE TITLE
编译报错 

### ISSUE THREAD

**Issue by iLoveNintendo** [Sky24n/common_utils#39]
../../../../development/flutter/.pub-cache/hosted/pub.flutter-io.cn/common_utils-2.0.2/lib/src/money_util.dart:87:59: Error: The method 'toInt' isn't defined for the class 'Decimal'.
 - 'Decimal' is from 'package:decimal/decimal.dart' ('../../../../development/flutter/.pub-cache/hosted/pub.flutter-io.cn/decimal-2.0.0/lib/decimal.dart').
Try correcting the name to the name of an existing method, or defining a method named 'toInt'.
    return NumUtil.multiplyDecStr(yuan.toString(), '100').toInt();
                                                          ^^^^^
../../../../development/flutter/.pub-cache/hosted/pub.flutter-io.cn/common_utils-2.0.2/lib/src/num_util.dart:134:29: Error: A value of type 'Rational' can't be returned from a function with return type 'Decimal'.
 - 'Rational' is from 'package:rational/rational.dart' ('../../../../development/flutter/.pub-cache/hosted/pub.flutter-io.cn/rational-2.0.0/lib/rational.dart').
 - 'Decimal' is from 'package:decimal/decimal.dart' ('../../../../development/flutter/.pub-cache/hosted/pub.flutter-io.cn/decimal-2.0.0/lib/decimal.dart').
    return Decimal.parse(a) / Decimal.parse(b);
                            ^

**Comment by 515445681** [comment]
一样，莫名其妙

**Comment by 515445681** [comment]
看样子是flutter升级导致的，人家没toInt方法了

**Comment by MRYIN123** [comment]
是decimal库更新了，decimal 2.0.0是11月29号发布的，然后里边去掉了toint方法，所以gg了

**Comment by MRYIN123** [comment]
可以暂时先把flutter安装目录里的 .pubcache里的这个库对应的依赖改下 decimal: ">=1.0.0 <3.0.0"改成decimal: ">=1.0.0 <2.0.0"这样，用1.5那个版本，2.0.0版本暂不支持。 我改了，还没去看看有没有bug

**Comment by lan2000** [comment]
我今天也出现了，是decimal 2.0.0升级了原因

**Comment by MRYIN123** [comment]
嗯，我查到了，原因和解决办法我贴上去了，就是提醒下



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月30日(星期二) 下午4:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Sky24n/common_utils] 编译报错  (Issue #39)





 
我今天也出现了，是decimal 2.0.0升级了原因
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jinliyuelong** [comment]
decimal 从1.5升级到2.0引起的，麻烦修改一下吧

**Comment by simplezhli** [comment]
可以使用依赖覆盖，以下配置添加到项目的pubspec.yaml中：
```
dependency_overrides:
  decimal: 1.5.0
```

**Comment by yaoyao2mm** [comment]
> 

有效

**Comment by Sky24n** [comment]
common_utils: ^2.1.0
