### ISSUE TITLE
decimal库更新了

### ISSUE THREAD

**Issue by kane619** [Sky24n/common_utils#40]

**Comment by kane619** [comment]
../../../../.pub-cache/hosted/pub.flutter-io.cn/common_utils-2.0.2/lib/src/money_util.dart:87:59: Error: The method 'toInt' isn't defined for the class 'Decimal'.
 - 'Decimal' is from 'package:decimal/decimal.dart' ('../../../../.pub-cache/hosted/pub.flutter-io.cn/decimal-2.0.0/lib/decimal.dart').
Try correcting the name to the name of an existing method, or defining a method named 'toInt'.
    return NumUtil.multiplyDecStr(yuan.toString(), '100').toInt();
                                                          ^^^^^
../../../../.pub-cache/hosted/pub.flutter-io.cn/common_utils-2.0.2/lib/src/num_util.dart:134:29: Error: A value of type 'Rational' can't be returned from a function with return type 'Decimal'.
 - 'Rational' is from 'package:rational/rational.dart' ('../../../../.pub-cache/hosted/pub.flutter-io.cn/rational-2.0.0/lib/rational.dart').
 - 'Decimal' is from 'package:decimal/decimal.dart' ('../../../../.pub-cache/hosted/pub.flutter-io.cn/decimal-2.0.0/lib/decimal.dart').
    return Decimal.parse(a) / Decimal.parse(b);

**Comment by Sky24n** [comment]
使用固定版本吧！没时间更新了，也没vpn
decimal: 1.5.0

**Comment by jiabin87428** [comment]
别啊哥，那么多人用呢，找时间更新一下吧

**Comment by simplezhli** [comment]
可以使用依赖覆盖，添加到项目的pubspec.yaml中：
```
dependency_overrides:
  decimal: 1.5.0
```

**Comment by kira2015** [comment]
希望快点更新吧

**Comment by Glorylan** [comment]
希望快点更新吧
