### ISSUE TITLE
flutter  Decimal  升级2.0.1 报错

### ISSUE THREAD

**Issue by yangchaoxun** [Sky24n/common_utils#45]
^
/D:/flutter_windows_2.0.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/common_utils-2.0.2/lib/src/num_util.dart:70:10: Error: Type 'Decimal' not found.
  static Decimal addDec(num a, num b) {
         ^^^^^^^
/D:/flutter_windows_2.0.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/common_utils-2.0.2/lib/src/num_util.dart:76:10: Error: Type 'Decimal' not found.
  static Decimal subtractDec(num a, num b) {
         ^^^^^^^
/D:/flutter_windows_2.0.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/common_utils-2.0.2/lib/src/num_util.dart:82:10: Error: Type 'Decimal' not found.
  static Decimal multiplyDec(num a, num b) {
         ^^^^^^^
/D:/flutter_windows_2.0.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/common_utils-2.0.2/lib/src/num_util.dart:88:10: Error: Type 'Decimal' not found.
  static Decimal divideDec(num a, num b) {
         ^^^^^^^
/D:/flutter_windows_2.0.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/common_utils-2.0.2/lib/src/num_util.dart:93:10: Error: Type 'Decimal' not found.
  static Decimal remainder(num a, num b) {
         ^^^^^^^
/D:/flutter_windows_2.0.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/common_utils-2.0.2/lib/src/num_util.dart:118:10: Error: Type 'Decimal' not found.
  static Decimal addDecStr(String a, String b) {
         ^^^^^^^
/D:/flutter_windows_2.0.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/common_utils-2.0.2/lib/src/num_util.dart:123:10: Error: Type 'Decimal' not found.
  static Decimal subtractDecStr(String a, String b) {
         ^^^^^^^
/D:/flutter_windows_2.0.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/common_utils-2.0.2/lib/src/num_util.dart:128:10: Error: Type 'Decimal' not found.
  static Decimal multiplyDecStr(String a, String b) {
         ^^^^^^^
/D:/flutter_windows_2.0.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/common_utils-2.0.2/lib/src/num_util.dart:133:10: Error: Type 'Decimal' not found.
  static Decimal divideDecStr(String a, String b) {
         ^^^^^^^
/D:/flutter_windows_2.0.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/common_utils-2.0.2/lib/src/num_util.dart:138:10: Error: Type 'Decimal' not found.
  static Decimal remainderDecStr(String a, String b) {
         ^^^^^^^
/D:/flutter_windows_2.0.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/common_utils-2.0.2/lib/src/num_util.dart:119:12: Error: Undefined name 'Decimal'.
    return Decimal.parse(a) + Decimal.parse(b);
           ^^^^^^^
/D:/flutter_windows_2.0.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/common_utils-2.0.2/lib/src/num_util.dart:119:31: Error: Undefined name 'Decimal'.
    return Decimal.parse(a) + Decimal.parse(b);
                              ^^^^^^^
/D:/flutter_windows_2.0.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/common_utils-2.0.2/lib/src/num_util.dart:124:12: Error: Undefined name 'Decimal'.
    return Decimal.parse(a) - Decimal.parse(b);
           ^^^^^^^
/D:/flutter_windows_2.0.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/common_utils-2.0.2/lib/src/num_util.dart:124:31: Error: Undefined name 'Decimal'.
    return Decimal.parse(a) - Decimal.parse(b);
                              ^^^^^^^
/D:/flutter_windows_2.0.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/common_utils-2.0.2/lib/src/num_util.dart:129:12: Error: Undefined name 'Decimal'.
    return Decimal.parse(a) * Decimal.parse(b);
           ^^^^^^^
/D:/flutter_windows_2.0.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/common_utils-2.0.2/lib/src/num_util.dart:129:31: Error: Undefined name 'Decimal'.
    return Decimal.parse(a) * Decimal.parse(b);
                              ^^^^^^^
/D:/flutter_windows_2.0.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/common_utils-2.0.2/lib/src/num_util.dart:134:12: Error: Undefined name 'Decimal'.
    return Decimal.parse(a) / Decimal.parse(b);
           ^^^^^^^
/D:/flutter_windows_2.0.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/common_utils-2.0.2/lib/src/num_util.dart:134:31: Error: Undefined name 'Decimal'.
    return Decimal.parse(a) / Decimal.parse(b);
                              ^^^^^^^
/D:/flutter_windows_2.0.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/common_utils-2.0.2/lib/src/num_util.dart:139:12: Error: Undefined name 'Decimal'.
    return Decimal.parse(a) % Decimal.parse(b);
           ^^^^^^^
/D:/flutter_windows_2.0.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/common_utils-2.0.2/lib/src/num_util.dart:139:31: Error: Undefined name 'Decimal'.
    return Decimal.parse(a) % Decimal.parse(b);
                              ^^^^^^^
/D:/flutter_windows_2.0.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/common_utils-2.0.2/lib/src/num_util.dart:144:12: Error: Undefined name 'Decimal'.
    return Decimal.parse(a) < Decimal.parse(b);
           ^^^^^^^
/D:/flutter_windows_2.0.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/common_utils-2.0.2/lib/src/num_util.dart:144:31: Error: Undefined name 'Decimal'.
    return Decimal.parse(a) < Decimal.parse(b);
                              ^^^^^^^
/D:/flutter_windows_2.0.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/common_utils-2.0.2/lib/src/num_util.dart:149:12: Error: Undefined name 'Decimal'.
    return Decimal.parse(a) <= Decimal.parse(b);
           ^^^^^^^
/D:/flutter_windows_2.0.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/common_utils-2.0.2/lib/src/num_util.dart:149:32: Error: Undefined name 'Decimal'.
    return Decimal.parse(a) <= Decimal.parse(b);
                               ^^^^^^^
/D:/flutter_windows_2.0.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/common_utils-2.0.2/lib/src/num_util.dart:154:12: Error: Undefined name 'Decimal'.
    return Decimal.parse(a) > Decimal.parse(b);
           ^^^^^^^
/D:/flutter_windows_2.0.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/common_utils-2.0.2/lib/src/num_util.dart:154:31: Error: Undefined name 'Decimal'.
    return Decimal.parse(a) > Decimal.parse(b);
                              ^^^^^^^
/D:/flutter_windows_2.0.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/common_utils-2.0.2/lib/src/num_util.dart:159:12: Error: Undefined name 'Decimal'.
    return Decimal.parse(a) >= Decimal.parse(b);
           ^^^^^^^
/D:/flutter_windows_2.0.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/common_utils-2.0.2/lib/src/num_util.dart:159:32: Error: Undefined name 'Decimal'.
    return Decimal.parse(a) >= Decimal.parse(b);

**Comment by Sky24n** [comment]
common_utils: ^2.1.0
