### ISSUE TITLE
想请教下，如何解决时区问题？例如：2018-11-23T03:23:55.626Z

### ISSUE THREAD

**Issue by shenxiang11** [Sky24n/common_utils#6]
2018-11-23T03:23:55.626Z
用您的工具现在是差了八小时，改如何解析呢

**Comment by Sky24n** [comment]
详细代码贴出来下

**Comment by shenxiang11** [comment]
```dart
    String formatedCreateAt = DateUtil.getDateStrByTimeStr(widget.createAt, format: DateFormat.YEAR_MONTH_DAY_HOUR_MINUTE);
```

数据库中我存的是，2018-11-23T03:23:55.626Z， 实际时间是2018-11-23 11:23
javascript可以正确解析，是浏览器自动按时区解析的么？
您的DateUtil这么解析也没错，但是想问问是否有按时区解析的功能，我怎么把差的8小时修正呢？

**Comment by Sky24n** [comment]
String formatedCreateAt = DateUtil.getDateStrByTimeStr(widget.createAt, format: DateFormat.YEAR_MONTH_DAY_HOUR_MINUTE, isUtc: true);

**Comment by shenxiang11** [comment]
谢谢

**Comment by shenxiang11** [comment]
不好意思又来了，不是支持这四个参数吗

```
getDateStrByTimeStr(String dateStr, {DateFormat format: DateFormat.NORMAL, String dateSeparate, String timeSeparate}) → String
```

**Comment by Sky24n** [comment]
用这个吧，那个是毫秒转时间的
DateUtil.getDateStrByDateTime( DateTime.parse("2018-11-23T03:23:55.626Z").toLocal(), format: DateFormat.YEAR_MONTH_DAY_HOUR_MINUTE);
