### ISSUE TITLE
什么时候加上加密类,文件目录操作类的封装?

### ISSUE THREAD

**Issue by lifetin** [Sky24n/common_utils#8]
什么时候加上加密类,文件目录操作类的封装?

**Comment by Sky24n** [comment]
加密倒是可以封装下；但是文件目录操作类的封装需要用path_provider库

**Comment by lifetin** [comment]
path_provider这个库很多插件都在用了.没这个没办法用图片缓存等.
看了下别的插件,很多插件都依赖了这个插件的. 

另外有没有位置适配计算的.发现有高和宽.没有top,left这个计算.
Positioned(                top: -45,)
在stack中用到这个后,位置有些偏了.

**Comment by Sky24n** [comment]
不是太懂呢的意思，是想根据屏幕适配吗？
[ScreenUtil](https://github.com/Sky24n/flustars) 不知道这个是否对你有用

**Comment by lifetin** [comment]
![44](https://user-images.githubusercontent.com/10474968/55944201-b2f9ed80-5c7a-11e9-957d-b21e49cb0065.png)

就是top,left,这种属性,好像screeUtil没有计算适配的吧?

**Comment by Sky24n** [comment]
代码能发全点吗

**Comment by lifetin** [comment]
![55](https://user-images.githubusercontent.com/10474968/55944559-6c58c300-5c7b-11e9-96d3-893b1284d1f3.png)

**Comment by Sky24n** [comment]
top也用ScreenUtil.getScaleH(context,-45);试下呢

**Comment by lifetin** [comment]
嗯.改了.可以. 待我换手机看看哈.谢谢了
期待你的进一步增加常用工具类...
